name: Test Github Auto Merge Protected
run-name: ${{ github.actor }} is automerging to master based on a merged pr to master-aux
on:
  pull_request_target:
    types:
      - closed
    branches:
      - master-aux

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: master
    - run: |
        echo Merging from master-aux to master automagically
        git config user.name github-actions
        git config user.email github-actions@github.com
        git branch --show
        git pull
        git diff origin/master-aux
        git merge origin/master-aux
        git push