name: Test Github Auto Merge
run-name: ${{ github.actor }} is automerging to master-aux based on a merged pr to master
on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master-aux
    - run: |
        echo Merging from master to master-aux automagically
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git merge master
        git push