name: Test Github Auto Merge
run-name: ${{ github.actor }} is testing an action based on a merged pr
on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged